# Generated by Django 4.1.7 on 2023-03-04 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian vehicle number (e.g. MH02AB1234).', regex='^[A-Z]{2}[0-9]{2}[A-Z]{2}[0-9]{4}$')])),
                ('vehicle_type', models.CharField(choices=[('Two Wheeler', 'Two Wheeler'), ('Three Wheeler', 'Three Wheeler'), ('Four Wheeler', 'Four Wheeler')], max_length=20)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_description', models.TextField()),
            ],
        ),
    ]
